//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSDiscovery
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery", ConfigurationName="WSDiscovery.TargetService", CallbackContract=typeof(WSDiscovery.TargetServiceCallback))]
    public interface TargetService
    {
        
        // CODEGEN: Generating message contract since the operation ProbeOp is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.xmlsoap.org/ws/2005/04/discovery/TargetService/ProbeOp")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ProbeOp(WSDiscovery.ProbeOp request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.xmlsoap.org/ws/2005/04/discovery/TargetService/ProbeOp")]
        System.Threading.Tasks.Task ProbeOpAsync(WSDiscovery.ProbeOp request);
        
        // CODEGEN: Generating message contract since the operation ResolveOp is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.xmlsoap.org/ws/2005/04/discovery/TargetService/ResolveOp")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ResolveOp(WSDiscovery.ResolveOp request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.xmlsoap.org/ws/2005/04/discovery/TargetService/ResolveOp")]
        System.Threading.Tasks.Task ResolveOpAsync(WSDiscovery.ResolveOp request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface TargetServiceCallback
    {
        
        // CODEGEN: Generating message contract since the operation HelloOp is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.xmlsoap.org/ws/2005/04/discovery/TargetService/HelloOp")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void HelloOp(WSDiscovery.HelloOp request);
        
        // CODEGEN: Generating message contract since the operation ByeOp is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.xmlsoap.org/ws/2005/04/discovery/TargetService/ByeOp")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ByeOp(WSDiscovery.ByeOp request);
        
        // CODEGEN: Generating message contract since the operation ProbeMatchOp is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.xmlsoap.org/ws/2005/04/discovery/TargetService/ProbeMatchOp")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ProbeMatchOp(WSDiscovery.ProbeMatchOp request);
        
        // CODEGEN: Generating message contract since the operation ResolveMatchOp is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://schemas.xmlsoap.org/ws/2005/04/discovery/TargetService/ResolveMatchOp")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ResolveMatchOp(WSDiscovery.ResolveMatchOp request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery")]
    public partial class HelloType
    {
        
        private EndpointReferenceType endpointReferenceField;
        
        private string typesField;
        
        private ScopesType scopesField;
        
        private string xAddrsField;
        
        private uint metadataVersionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing", Order=0)]
        public EndpointReferenceType EndpointReference
        {
            get
            {
                return this.endpointReferenceField;
            }
            set
            {
                this.endpointReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Types
        {
            get
            {
                return this.typesField;
            }
            set
            {
                this.typesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ScopesType Scopes
        {
            get
            {
                return this.scopesField;
            }
            set
            {
                this.scopesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string XAddrs
        {
            get
            {
                return this.xAddrsField;
            }
            set
            {
                this.xAddrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public uint MetadataVersion
        {
            get
            {
                return this.metadataVersionField;
            }
            set
            {
                this.metadataVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class EndpointReferenceType
    {
        
        private AttributedURI addressField;
        
        private ReferencePropertiesType referencePropertiesField;
        
        private ReferenceParametersType referenceParametersField;
        
        private AttributedQName portTypeField;
        
        private ServiceNameType serviceNameField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AttributedURI Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ReferencePropertiesType ReferenceProperties
        {
            get
            {
                return this.referencePropertiesField;
            }
            set
            {
                this.referencePropertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ReferenceParametersType ReferenceParameters
        {
            get
            {
                return this.referenceParametersField;
            }
            set
            {
                this.referenceParametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AttributedQName PortType
        {
            get
            {
                return this.portTypeField;
            }
            set
            {
                this.portTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ServiceNameType ServiceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class AttributedURI
    {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery")]
    public partial class ResolveMatchType
    {
        
        private EndpointReferenceType endpointReferenceField;
        
        private string typesField;
        
        private ScopesType scopesField;
        
        private string xAddrsField;
        
        private uint metadataVersionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing", Order=0)]
        public EndpointReferenceType EndpointReference
        {
            get
            {
                return this.endpointReferenceField;
            }
            set
            {
                this.endpointReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Types
        {
            get
            {
                return this.typesField;
            }
            set
            {
                this.typesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ScopesType Scopes
        {
            get
            {
                return this.scopesField;
            }
            set
            {
                this.scopesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string XAddrs
        {
            get
            {
                return this.xAddrsField;
            }
            set
            {
                this.xAddrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public uint MetadataVersion
        {
            get
            {
                return this.metadataVersionField;
            }
            set
            {
                this.metadataVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery")]
    public partial class ScopesType
    {
        
        private string matchByField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string MatchBy
        {
            get
            {
                return this.matchByField;
            }
            set
            {
                this.matchByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery")]
    public partial class ResolveMatchesType
    {
        
        private ResolveMatchType resolveMatchField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResolveMatchType ResolveMatch
        {
            get
            {
                return this.resolveMatchField;
            }
            set
            {
                this.resolveMatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery")]
    public partial class ResolveType
    {
        
        private EndpointReferenceType endpointReferenceField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing", Order=0)]
        public EndpointReferenceType EndpointReference
        {
            get
            {
                return this.endpointReferenceField;
            }
            set
            {
                this.endpointReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery")]
    public partial class ProbeMatchType
    {
        
        private EndpointReferenceType endpointReferenceField;
        
        private string typesField;
        
        private ScopesType scopesField;
        
        private string xAddrsField;
        
        private uint metadataVersionField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing", Order=0)]
        public EndpointReferenceType EndpointReference
        {
            get
            {
                return this.endpointReferenceField;
            }
            set
            {
                this.endpointReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Types
        {
            get
            {
                return this.typesField;
            }
            set
            {
                this.typesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ScopesType Scopes
        {
            get
            {
                return this.scopesField;
            }
            set
            {
                this.scopesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string XAddrs
        {
            get
            {
                return this.xAddrsField;
            }
            set
            {
                this.xAddrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public uint MetadataVersion
        {
            get
            {
                return this.metadataVersionField;
            }
            set
            {
                this.metadataVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery")]
    public partial class ProbeMatchesType
    {
        
        private ProbeMatchType[] probeMatchField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProbeMatch", Order=0)]
        public ProbeMatchType[] ProbeMatch
        {
            get
            {
                return this.probeMatchField;
            }
            set
            {
                this.probeMatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery")]
    public partial class ProbeType
    {
        
        private string typesField;
        
        private ScopesType scopesField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Types
        {
            get
            {
                return this.typesField;
            }
            set
            {
                this.typesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ScopesType Scopes
        {
            get
            {
                return this.scopesField;
            }
            set
            {
                this.scopesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery")]
    public partial class ByeType
    {
        
        private EndpointReferenceType endpointReferenceField;
        
        private string typesField;
        
        private ScopesType scopesField;
        
        private string xAddrsField;
        
        private uint metadataVersionField;
        
        private bool metadataVersionFieldSpecified;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing", Order=0)]
        public EndpointReferenceType EndpointReference
        {
            get
            {
                return this.endpointReferenceField;
            }
            set
            {
                this.endpointReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Types
        {
            get
            {
                return this.typesField;
            }
            set
            {
                this.typesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ScopesType Scopes
        {
            get
            {
                return this.scopesField;
            }
            set
            {
                this.scopesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string XAddrs
        {
            get
            {
                return this.xAddrsField;
            }
            set
            {
                this.xAddrsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public uint MetadataVersion
        {
            get
            {
                return this.metadataVersionField;
            }
            set
            {
                this.metadataVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MetadataVersionSpecified
        {
            get
            {
                return this.metadataVersionFieldSpecified;
            }
            set
            {
                this.metadataVersionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class ServiceNameType
    {
        
        private string portNameField;
        
        private System.Xml.XmlQualifiedName valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
        public string PortName
        {
            get
            {
                return this.portNameField;
            }
            set
            {
                this.portNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.Xml.XmlQualifiedName Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class AttributedQName
    {
        
        private System.Xml.XmlQualifiedName valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.Xml.XmlQualifiedName Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class ReferenceParametersType
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/ws/2004/08/addressing")]
    public partial class ReferencePropertiesType
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloOp
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery", Order=0)]
        public WSDiscovery.HelloType Hello;
        
        public HelloOp()
        {
        }
        
        public HelloOp(WSDiscovery.HelloType Hello)
        {
            this.Hello = Hello;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ByeOp
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery", Order=0)]
        public WSDiscovery.ByeType Bye;
        
        public ByeOp()
        {
        }
        
        public ByeOp(WSDiscovery.ByeType Bye)
        {
            this.Bye = Bye;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProbeOp
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery", Order=0)]
        public WSDiscovery.ProbeType Probe;
        
        public ProbeOp()
        {
        }
        
        public ProbeOp(WSDiscovery.ProbeType Probe)
        {
            this.Probe = Probe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProbeMatchOp
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery", Order=0)]
        public WSDiscovery.ProbeMatchesType ProbeMatches;
        
        public ProbeMatchOp()
        {
        }
        
        public ProbeMatchOp(WSDiscovery.ProbeMatchesType ProbeMatches)
        {
            this.ProbeMatches = ProbeMatches;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResolveOp
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery", Order=0)]
        public WSDiscovery.ResolveType Resolve;
        
        public ResolveOp()
        {
        }
        
        public ResolveOp(WSDiscovery.ResolveType Resolve)
        {
            this.Resolve = Resolve;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResolveMatchOp
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery", Order=0)]
        public WSDiscovery.ResolveMatchesType ResolveMatches;
        
        public ResolveMatchOp()
        {
        }
        
        public ResolveMatchOp(WSDiscovery.ResolveMatchesType ResolveMatches)
        {
            this.ResolveMatches = ResolveMatches;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface TargetServiceChannel : WSDiscovery.TargetService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class TargetServiceClientBase : System.ServiceModel.DuplexClientBase<WSDiscovery.TargetService>, WSDiscovery.TargetService
    {
        
        public TargetServiceClientBase(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WSDiscovery.TargetService.ProbeOp(WSDiscovery.ProbeOp request)
        {
            base.Channel.ProbeOp(request);
        }
        
        public void ProbeOp(WSDiscovery.ProbeType Probe)
        {
            WSDiscovery.ProbeOp inValue = new WSDiscovery.ProbeOp();
            inValue.Probe = Probe;
            ((WSDiscovery.TargetService)(this)).ProbeOp(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task WSDiscovery.TargetService.ProbeOpAsync(WSDiscovery.ProbeOp request)
        {
            return base.Channel.ProbeOpAsync(request);
        }
        
        public System.Threading.Tasks.Task ProbeOpAsync(WSDiscovery.ProbeType Probe)
        {
            WSDiscovery.ProbeOp inValue = new WSDiscovery.ProbeOp();
            inValue.Probe = Probe;
            return ((WSDiscovery.TargetService)(this)).ProbeOpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void WSDiscovery.TargetService.ResolveOp(WSDiscovery.ResolveOp request)
        {
            base.Channel.ResolveOp(request);
        }
        
        public void ResolveOp(WSDiscovery.ResolveType Resolve)
        {
            WSDiscovery.ResolveOp inValue = new WSDiscovery.ResolveOp();
            inValue.Resolve = Resolve;
            ((WSDiscovery.TargetService)(this)).ResolveOp(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task WSDiscovery.TargetService.ResolveOpAsync(WSDiscovery.ResolveOp request)
        {
            return base.Channel.ResolveOpAsync(request);
        }
        
        public System.Threading.Tasks.Task ResolveOpAsync(WSDiscovery.ResolveType Resolve)
        {
            WSDiscovery.ResolveOp inValue = new WSDiscovery.ResolveOp();
            inValue.Resolve = Resolve;
            return ((WSDiscovery.TargetService)(this)).ResolveOpAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.xmlsoap.org/ws/2005/04/discovery", ConfigurationName="WSDiscovery.DiscoveryProxy")]
    public interface DiscoveryProxy
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface DiscoveryProxyChannel : WSDiscovery.DiscoveryProxy, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DiscoveryProxyClient : System.ServiceModel.ClientBase<WSDiscovery.DiscoveryProxy>, WSDiscovery.DiscoveryProxy
    {
        
        public DiscoveryProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
    
    public class HelloOpReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public HelloOpReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public WSDiscovery.HelloOp request
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((WSDiscovery.HelloOp)(this.results[0]));
            }
        }
    }
    
    public class ByeOpReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public ByeOpReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public WSDiscovery.ByeOp request
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((WSDiscovery.ByeOp)(this.results[0]));
            }
        }
    }
    
    public class ProbeMatchOpReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public ProbeMatchOpReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public WSDiscovery.ProbeMatchOp request
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((WSDiscovery.ProbeMatchOp)(this.results[0]));
            }
        }
    }
    
    public class ResolveMatchOpReceivedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        public ResolveMatchOpReceivedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        public WSDiscovery.ResolveMatchOp request
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((WSDiscovery.ResolveMatchOp)(this.results[0]));
            }
        }
    }
    
    public partial class TargetServiceClient : TargetServiceClientBase
    {
        
        public TargetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                this(new TargetServiceClientCallback(), binding, remoteAddress)
        {
        }
        
        private TargetServiceClient(TargetServiceClientCallback callbackImpl, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(new System.ServiceModel.InstanceContext(callbackImpl), binding, remoteAddress)
        {
            callbackImpl.Initialize(this);
        }
        
        public event System.EventHandler<HelloOpReceivedEventArgs> HelloOpReceived;
        
        public event System.EventHandler<ByeOpReceivedEventArgs> ByeOpReceived;
        
        public event System.EventHandler<ProbeMatchOpReceivedEventArgs> ProbeMatchOpReceived;
        
        public event System.EventHandler<ResolveMatchOpReceivedEventArgs> ResolveMatchOpReceived;
        
        private void OnHelloOpReceived(object state)
        {
            if ((this.HelloOpReceived != null))
            {
                object[] results = ((object[])(state));
                this.HelloOpReceived(this, new HelloOpReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnByeOpReceived(object state)
        {
            if ((this.ByeOpReceived != null))
            {
                object[] results = ((object[])(state));
                this.ByeOpReceived(this, new ByeOpReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnProbeMatchOpReceived(object state)
        {
            if ((this.ProbeMatchOpReceived != null))
            {
                object[] results = ((object[])(state));
                this.ProbeMatchOpReceived(this, new ProbeMatchOpReceivedEventArgs(results, null, false, null));
            }
        }
        
        private void OnResolveMatchOpReceived(object state)
        {
            if ((this.ResolveMatchOpReceived != null))
            {
                object[] results = ((object[])(state));
                this.ResolveMatchOpReceived(this, new ResolveMatchOpReceivedEventArgs(results, null, false, null));
            }
        }
        
        private class TargetServiceClientCallback : object, TargetServiceCallback
        {
            
            private TargetServiceClient proxy;
            
            public void Initialize(TargetServiceClient proxy)
            {
                this.proxy = proxy;
            }
            
            public void HelloOp(WSDiscovery.HelloOp request)
            {
                this.proxy.OnHelloOpReceived(new object[] {
                            request});
            }
            
            public void ByeOp(WSDiscovery.ByeOp request)
            {
                this.proxy.OnByeOpReceived(new object[] {
                            request});
            }
            
            public void ProbeMatchOp(WSDiscovery.ProbeMatchOp request)
            {
                this.proxy.OnProbeMatchOpReceived(new object[] {
                            request});
            }
            
            public void ResolveMatchOp(WSDiscovery.ResolveMatchOp request)
            {
                this.proxy.OnResolveMatchOpReceived(new object[] {
                            request});
            }
        }
    }
}
